name: Deploy site files

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps: # 自动化步骤
    - name: Checkout
    - uses: actions/checkout@master # 1、下载代码仓库

    - name: Build and Deploy # 2、rsync 推文件
      uses: JamesIves/github-pages-deploy-action@master # vuepress github actions
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 引用配置，SSH私钥
        BRANCH: master
        ARGS: -avz --delete --exclude='*.pyc'   # rsync参数，排除.pyc文件
        SERVER_PORT: '22'  # SSH端口
        FOLDER: .vuepress/dist  # 要推送的文件夹，路径相对于代码仓库的根目录
        SERVER_DESTINATION: /www/zakBlog/   # 部署到目标文件夹
   